### ISSUE TITLE
The training part doesn't work for me

### ISSUE THREAD

**Issue by mmarcon** [alvinwan/riot#1]
Hey, very interesting project!

I have an issue with making it work though: I cloned the repo, installed the dependencies, ran a scan and I get this error in the dev console:

<img width="545" alt="screen shot 2018-08-31 at 10 27 40" src="https://user-images.githubusercontent.com/761042/44901766-97079400-ad08-11e8-9598-7716590fbf58.png">

**Comment by alvinwan** [comment]
@mmarcon Thanks! More importantly, thanks for reporting. I was trying to filter out `.DS_Store` and did so incorrectly. Just pushed a fix. Just let me know if you run into other issues.
